server:
    port: 8686
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.212:3307/test?characterEncoding=UTF-8&
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      #项目重新编译报404问题
      poll-interval: 3000
      quiet-period: 1000

#mybatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.ringo.vo #存放bean对象
  configuration:
    #下划线驼峰配置
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}[%thread]%-5level %logger-%msg%n"
    level: debug
  file:
    path: "."
    name: "springboot.log"